// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RKSOFTWARESOLUTIONS.Models;

#nullable disable

namespace RKSOFTWARESOLUTIONS.Migrations
{
    [DbContext(typeof(AksharaContext))]
    partial class AksharaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RKSOFTWARESOLUTIONS.Models.Login", b =>
                {
                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.ToTable("Login", (string)null);
                });

            modelBuilder.Entity("RKSOFTWARESOLUTIONS.Models.RegistrationForm", b =>
                {
                    b.Property<int?>("ConfirmPassword")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("NewPassword")
                        .HasColumnType("int");

                    b.Property<string>("NewUserName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.ToTable("RegistrationForm", (string)null);
                });

            modelBuilder.Entity("RKSOFTWARESOLUTIONS.Models.Rksolution", b =>
                {
                    b.Property<int?>("Deptno")
                        .HasColumnType("int");

                    b.Property<int?>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Job")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Salary")
                        .HasColumnType("int");

                    b.ToTable("RKSolutions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
